version: 2

sources:
  - name: institution_src
    database: USER_DB_LEMMING
    schema: RAW
    tables:
      - name: institution_outcomes          # logical name used in source() in dbt
        identifier: COLLEGE_SCORECARD_DATA  # actual table name in Snowflake

  - name: jobs_src
    database: USER_DB_GOPHER
    schema: RAW
    tables:
      - name: job_listings              # used in source('jobs_src','job_listings')
        identifier: JOB_LISTINGS        # physical table

  - name: warn_src
    database: USER_DB_GIRAFFE
    schema: RAW
    tables:
      - name: warn_layoffs              # used in source('warn_src','warn_layoffs')
        identifier: WARN_EVENTS         # physical table

  - name: bls_src
    database: USER_DB_HYENA
    schema: RAW                   # if that’s truly where the table lives
    tables:
      - name: bls_occupations           # used in source('bls_src','bls_occupations')
        identifier: BLS_EMPLOYMENT_PROJECTIONS

  - name: lookups_src
    database: USER_DB_GOPHER
    schema: RAW
    tables:
      - name: lookup_job_categories
        identifier: LOOKUP_JOB_CATEGORIES
      - name: lookup_warn_industries
        identifier: LOOKUP_WARN_INDUSTRIES
      - name: lookup_bls_occupations
        identifier: LOOKUP_BLS_OCCUPATIONS
