version: 2

models:

  # -------------------------------------------------------------------
  # Institution Staging
  # -------------------------------------------------------------------
  - name: stg_institution
    description: "Cleans and enriches institution outcomes data (Scorecard-like). Produces ROI and value metrics."
    columns:
      - name: INSTITUTION_ID
        description: "Primary identifier for the institution."
        tests: [not_null]

      - name: INSTITUTION_NAME
        description: "Name of the institution."

      - name: STATE
        description: "State where the institution is located."
        tests: [not_null]

      - name: ROI_IN_STATE
        description: "ROI metric based on in-state tuition."

      - name: ROI_OUT_OF_STATE
        description: "ROI metric based on out-of-state tuition."

      - name: DEBT_TO_EARNINGS_RATIO
        description: "Debt burden relative to student earnings 10 years after enrollment."

      - name: VALUE_INDEX
        description: "Earnings (10 years) minus net price—measure of institutional value."


  # -------------------------------------------------------------------
  # Job Listings Staging
  # -------------------------------------------------------------------
  - name: stg_jobs
    description: "Cleaned job postings enriched with occupation_group from category lookup."
    columns:
      - name: JOB_ID
        description: "Unique identifier for each job posting."
        tests: [unique, not_null]

      - name: STATE
        description: "State where job is located."
        tests: [not_null]

      - name: CATEGORY
        description: "Job listing category label."

      - name: OCCUPATION_GROUP
        description: "Mapped occupation group for this job category (from lookup)."
        tests: [not_null]

      - name: POSTING_TS
        description: "Posting timestamp converted to timestamp_ntz."


  # -------------------------------------------------------------------
  # WARN Layoffs Staging
  # -------------------------------------------------------------------
  - name: stg_warn
    description: "Cleaned WARN layoffs enriched with occupation_group from industry lookup."
    columns:
      - name: STATE
        description: "State of employer layoff event."
        tests: [not_null]

      - name: INDUSTRY
        description: "Industry classification from WARN filing."

      - name: OCCUPATION_GROUP
        description: "Mapped occupation group from WARN industry lookup."
        tests: [not_null]

      - name: NUMBER_OF_WORKERS
        description: "Number of workers affected."
        tests: [not_null]


  # -------------------------------------------------------------------
  # BLS Occupations Staging
  # -------------------------------------------------------------------
  - name: stg_bls
    description: "Cleaned BLS occupational data enriched with occupation_group lookup."
    columns:
      - name: OCCUPATION_TITLE
        description: "BLS SOC occupation title."
        tests: [not_null]

      - name: OCCUPATION_GROUP
        description: "Mapped occupation group from the BLS occupation lookup."
        tests: [not_null]

      - name: EMPLOYMENT_PERCENT_CHANGE_2024_2034
        description: "Projected growth percentage for the occupation."

      - name: MEDIAN_ANNUAL_WAGE_2024
        description: "Median wage from BLS OES dataset."


  # -------------------------------------------------------------------
  # Consolidated Lookups Staging (Optional)
  # -------------------------------------------------------------------
  - name: stg_lookups
    description: "Unified lookup that merges all CATEGORY, INDUSTRY, and OCCUPATION_TITLE mappings into a single table."
    columns:
      - name: LOOKUP_TYPE
        description: "The type of lookup value (CATEGORY, INDUSTRY, OCCUPATION_TITLE)."
        tests:
          - accepted_values:
              values: ["CATEGORY", "INDUSTRY", "OCCUPATION_TITLE"]

      - name: RAW_VALUE
        description: "Raw category/industry/title from datasets."
        tests: [not_null]

      - name: OCCUPATION_GROUP
        description: "Mapped occupation group based on 25 standardized occupation groups."
        tests: [not_null]
